//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public int phone { get; set; }
        public System.DateTime dateOfJoin { get; set; }
        public int addressID { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string line1 { get; set; }
        public string line2 { get; set; }
        public string province { get; set; }
        public string zipCode { get; set; }
        public string country { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
